version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - my-net

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
